name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点自动检查更新
  workflow_dispatch: # 允许你手动点击按钮立刻同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 第一步：必须先拉取你仓库的代码环境，否则后面会报错
      - name: Checkout
        uses: actions/checkout@v4

      # 第二步：去原作者那里拉代码并合并到你的 main 分支
      - name: Sync with Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: mtvpls/MoonTVPlus
          upstream_sync_branch: main
          test_mode: false
